version: "3.8"

services:
    api:
        build:
            context: ./gemshopAPI
            dockerfile: ./Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./gemshopAPI:/var/www/html
    nginx:
        image:  nginx:latest
        restart: unless-stopped
        networks:
            - net
        ports:
            - 80:80
        depends_on:
            - api
        volumes:
            - ./gemshopAPI:/var/www/html
            - ./gemshopAPI/docker/nginx/logs:/var/log/nginx
            - ./gemshopAPI/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
              POSTGRES_PASSWORD: example
        networks:
            - net
        depends_on:
            - api
        ports:
            - 8081:8081
        volumes:
            - ./gemshopAPI/docker/data/postgres:/var/log/postgresql

networks:
    net:
        driver: bridge
